spring:
  host: 127.0.0.1
  port: 5672
  virtualHost: /
  userName: guest
  password: guest
  cloud:
    openfeign:
      client:
        config:
          Account:
            url: http://localhost:8080
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full


  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true