spring:
  security:
    jwt:
      key: bcdedit12312as
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 2
      auto-commit: true
  mail:
    host: smtp.163.com
    username: m19375389028@163.com
    password: XXNBCJDOLWKCIVRU
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.163.com
  rabbitmq:
    #发送者的消息确认
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
          # 指定消息在没有被队列接收时是否强行退回还是直接丢弃:ReturnCallback.returnedMessage消息未送达回调（true）
         mandatory: true
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: manual
        prefetch: 1
        retry:
          # 是否开启重试机制
          enabled: true
          # 默认是3,是一共三次，而不是重试三次，三次包含了第一执行，所以只重试了两次
          max-attempts: 3
          # 重试间隔时间。毫秒
          initial-interval: 2000


  minio:
    endpoint: http://localhost:9000
    username: "minio"
    password: "password"
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
